[cosmic-ray]
module-path = "serin/d1_2_gateway_io/d2_1_io_discord/d3_1_pipeline_init"
timeout = 999999
excluded-modules = [
    "*/__init__.py",
    "*/tests/*",
]
test-command = "uv run pytest tests/bot_pipeline_init/"

[cosmic-ray.distributor]
name = "local"
workers = 10
