[cosmic-ray]
module-path = "serin/d1_1_pipeline_flow/d2_2_flow_ingest/d3_2_ingest_core/d4_1_core_perception"
timeout = 999999
excluded-modules = [
    "*/__init__.py",
    "*/tests/*",
]
test-command = "uv run pytest tests/perception/"

[cosmic-ray.distributor]
name = "local"
workers = 10
