[cosmic-ray]
module-path = "serin"
excluded-modules = [
    "*/__init__.py",
    "*/__main__.py",
    "*/setup.py",
    "*/conftest.py",
    "*/Tests/*",
    "*/tests/*",
]
test-command = "uv run pytest tests/"

[cosmic-ray.distributor]
name = "local"
workers = 12
