[cosmic-ray]
module-path = "serin/d1_5_ops_tooling/d2_1_control_panel/d3_2_panel_server"
timeout = 999999
excluded-modules = [
    "*/__init__.py",
    "*/tests/*",
]
test-command = "uv run pytest tests/server/"

[cosmic-ray.distributor]
name = "local"
workers = 10
